### ISSUE TITLE
Add package to PyPI

### ISSUE THREAD

**Issue by Elektordi** [Elektordi/obs-websocket-py#1]
Follow up issue for adding obs-websocket-py to PyPI (pip repository) as requested by @Palakis

**Comment by Palakis** [comment]
Could be handy: http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by Elektordi** [comment]
Done: https://pypi.python.org/pypi/obs-websocket-py ! :smiley: 
Just tested in a clean venv, it's working out of the box.

(Btw, I also found his site, explanations were good, but it seems down today, domain is not resolving... :disappointed: )

**Comment by Palakis** [comment]
neat!
