### ISSUE TITLE
Heartbeat addition patch

### ISSUE THREAD

**Issue by masikh** [Elektordi/obs-websocket-py#10]
Adding the two classes below to the request.py and event.py file will enable the heartbeat which was introduced lately in the obs-websocket implementation from: https://github.com/Palakis/obs-websocket/

Is it possible that you/anyone could add those classes to these files?

Kind regards,

Robert Nagtegaal
masikh@gmail.com

**request.py:**
```javascript
class SetHeartBeat(base_classes.BaseRequest):
    def __init__(self, enable):
        base_classes.BaseRequest.__init__(self)
        self.name = "SetHeartbeat"
        self.dataout["enable"] = enable
```

**event.py:**
```javascript        
class Heartbeat(base_classes.BaseEvent):
    def __init__(self):
        base_classes.BaseEvent.__init__(self)
        self.name = "Heartbeat"
        self.datain["current-profile"] = None
        self.datain["current-scene"] = None
        self.datain["pulse"] = False
        self.datain["rec-timecode"] = None
        self.datain["recording"] = None
        self.datain["streaming"] = None
        self.datain["total-record-bytes"] = None
        self.datain["total-record-frames"] = None
        self.datain["total-record-time"] = None
```
see also: https://github.com/Elektordi/obs-websocket-py/pulls

**Comment by masikh** [comment]
Adding above class to the events.py file will enable the output of Heartbeat messages with the latest (you have to build from latest source) obs-websocket 'release'(*)

(*) its in the master but no official release yet!

**Comment by Elektordi** [comment]
Thanks for the PR. I'll take a look to it this weekend.

**Comment by masikh** [comment]
Obsoleted by pull request #10 and #11
