### ISSUE TITLE
PyPi Build Not Compatible with 3.x

### ISSUE THREAD

**Issue by dmadison** [Elektordi/obs-websocket-py#16]
Although the repository is 3.x compatible (1b97dc81fe50fedb03918e107298f2c17a76c21b) and is stated as such in [the plugin README](https://github.com/Palakis/obs-websocket#for-developers), the current version on PyPi does not have these changes.

It would be nice if you could push the latest version to PyPi so the module installed via pip is 3.x compatible :smile:.

**Comment by Elektordi** [comment]
I'll try to push a 0.3 release on PyPi by next week.

**Comment by Elektordi** [comment]
It's live: https://pypi.org/project/obs-websocket-py/0.3/
