### ISSUE TITLE
Requests can't find items or scenes

### ISSUE THREAD

**Issue by JohnnyBlaze420** [Elektordi/obs-websocket-py#2]
#### Issue type
- [X] Bug
- [ ] Feature request
- [X] Other

#### Description
While using Python and obs-websocket-py trying to use SetCurrentScene results in

`<SetCurrentScene request({u"error" : u"requested scene does not exist"}) called: failed ({"scene-name" : u"s2"})>`

or any other name results in "scene does not exist" error, even if the scene does exists and is read by using GetSceneList(). Same happens for setting source properties - the module always returns a "not found" error, even if scenes / sources can be found in the scene via obs-websocket.py.

#### Steps to reproduce
Make two scenes in OBS, "s1" and "s2". Then:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import obswebsocket as obsw
import obswebsocket.requests as obsr

client = obsw.obsws("localhost", 4444, "password")
client.connect()
scenes = client.call(obsr.GetSceneList()).dataout["scenes"]
newScene = scenes[1]
res = client.call(obsr.SetCurrentScene(newScene["name"]))
print res
client.disconnect()
```

#### Technical information
- **Operating System** : Windows 7 Pro x64 SP1
- **OBS Studio version** : 19.0.3 x32
- **Python version**: 2.7.13 x32
Using obs-websocket version 4.0 and obs-websocket-py version 0.1.

**Comment by Elektordi** [comment]
Hello,

Your code is working on my Linux computer. I'll try to find a Windows one to test that.

Best regards.

**Comment by JohnnyBlaze420** [comment]
Elektrodil, thank you for taking interest in this one! I'll test another Win7 setup today and bring back the results.

**Comment by Elektordi** [comment]
There was a bug just corrected in master about some datain/dataout mismatch (0f9adb66).
Maybe your problem is a side effect of this. Could you pull master and try again?

By the way, you should use `.getScenes()` instead of `.dataout["scenes"]` in your code.
There is a similar use in `samples/switch_scene.py`

**Comment by markusbaker** [comment]
Thank you so much for this! Updating to [the current master](https://github.com/Elektordi/obs-websocket-py/commit/8e6d4fc7ab4bd6ae83e892da9325d42c9ffd453a) (instead of using the pip version) resolved my issue running the [scene switcher example](https://github.com/Elektordi/obs-websocket-py/blob/master/samples/switch_scenes.py).

**Comment by Elektordi** [comment]
Third people to confirm new version is working, pushing update to PyPI. Thanks @markusbaker for testing.

@JohnnyBlaze420 can you confirm it resolved your issue?

**Comment by JohnnyBlaze420** [comment]
@Elektordi tested with the switch_scene.py sample file on:
Win7x64, OBS 19.0.3 x32 and x64, Python 2.7.13 x32.
I'm glad to report that it **works like a charm** now, switching scenes without any problems, I think other requests will now work as well. Thank you so much for taking your time and resolving this issue, I was waiting with streaming until I could use this module in my custom bot. :)

One more final question: do you plan on releasing a Python 3 version (some syntax issues in modules), or should we just tinker with it on our own? Anyway, issue resolved, thank you so much again!

**Comment by Elektordi** [comment]
Thanks. I'm closing this issue.

For Py3 release, I created a new issue for this matter: #5 You can subscribe to it if you want.
