### ISSUE TITLE
Installation on Windows Failure

### ISSUE THREAD

**Issue by Pascalao** [Elektordi/obs-websocket-py#21]
Hi,
I can't install obs-websocket-py.
Over pip install obs-websocket-py, I get:

Collecting obs-websocket-py
  Using cached https://files.pythonhosted.org/packages/2c/82/125306f049d7517f6cbae078fe0dc4cb82df08d5a2b1018b7bbd753eadc8/obs-websocket-py-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\pascal\appdata\local\temp\pip-install-d1x5gc\obs-websocket-py\setup.py", line 9, in <module>
        from generate_classes import generate_classes
    ImportError: No module named generate_classes

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\pascal\appdata\local\temp\pip-install-d1x5gc\obs-websocket-py\

I need the library for python2.7.
When I try it to install from a cloned git repo, I get:

Processing c:\users\pascal\downloads\obs-websocket-py-master\obs-websocket-py-master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\pascal\appdata\local\temp\pip-req-build-lh8uf8\setup.py", line 10, in <module>
        from obswebsocket import __version__
      File "obswebsocket\__init__.py", line 8, in <module>
        from .core import obsws
      File "obswebsocket\core.py", line 18, in <module>
        from . import events
    ImportError: cannot import name events

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\pascal\appdata\local\temp\pip-req-build-lh8uf8\

And I installed events 0.3 with pip. 
>pip install events
>Requirement already satisfied: events in c:\python27\lib\site-packages (0.3)

May the import of events are not correct?
Or something else? 

I hope you can help.

best regards

**Comment by Elektordi** [comment]
Hello,
(Sorry for the delay... :/ )

Just released version 0.4, it fixes a bug in the setup process, could you try again?

Best regards,

**Comment by Elektordi** [comment]
No news is good news... Fell free to open it again if the problem is still here!
(I haven't got any Windows setup, only Linux, so I cannot test myself...)
