### ISSUE TITLE
Error on IronPython 2.7

### ISSUE THREAD

**Issue by IMarkoMC** [Elektordi/obs-websocket-py#22]
First of all, i want to ask, is compatible with ironpython? almost all libraries of python are compatible,
If it is when i try to connect to the server i get an error:
obswebsocket.exceptions.ConnectionFailure: [Errno 10044] The support for the specified socket type does not exist in this address family
You may ask. Why i'm using IronPython and not Python, the answer is simple, i need load some .DLLs and the Pythonnet lib dosnt work on python because the stupid NTFS security thing of windows

C:\Windows\system32>ipy
IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import time
>>> import logging
>>> logging.basicConfig(level=logging.INFO)
>>> from obswebsocket import obsws, requests
>>> host = 'localhost'
>>> port = 4444
>>> password = "test"
>>> ws = obsws(host, port, password)
>>> ws.connect()
INFO:obswebsocket.core:Connecting...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\obswebsocket\core.py", line 72, in connect
obswebsocket.exceptions.ConnectionFailure: [Errno 10044] The support for the specified socket type does not exist in this address family

**Comment by IMarkoMC** [comment]
**SOLVED: Copy SocketServer and socket from C:\Python27\lib and pasted on the IronPython lib Folder (C:\Program Files\IronPython 2.7\Lib) **
Now works!

**Comment by IMarkoMC** [comment]
> 
> 
> It seems you had an answer on github, but the comment disappeard, I don't know why...
> 
> > **SOLVED: Copy SocketServer and socket from C:\Python27\lib and pasted on the IronPython lib Folder (C:\Program Files\IronPython 2.7\Lib) **
> > Now works!
> 
> Does this fixed the problem?

kind of, it worked very little was very glitchy and then I had to install IronPython (pip and other modules stopped working)

**Comment by IMarkoMC** [comment]
Finally after that i decide to use a Python3 script as main (to  handle all OBS - controller communications) and use the IronPython for the DLL management.

**Comment by Elektordi** [comment]
Ok, I'll close the issue, but you can still comment it after.
Have a good evening!

**Comment by kevindarby** [comment]
Did anyone get this to work?  @IMarkoMC ?

**Comment by XoTRC69** [comment]
contact me on instagram @ xotrc9490 immediately ImarkoMC. skid

**Comment by IMarkoMC** [comment]
> contact me on instagram @ xotrc9490 immediately ImarkoMC. skid

Who do you think you are?? lmfao
