### ISSUE TITLE
Can't get audio source mute status

### ISSUE THREAD

**Issue by elfchief** [Elektordi/obs-websocket-py#28]
At least in the current (0.4) version, it is impossible to get the mute status of an audio source, presumably due to using the wrong key when getMute() is called.

```
source = client.call(obswebsocket.requests.GetVolume("Line 1 (Streaming Music)"))
print source
<GetVolume request ({'source': 'Line 1 (Streaming Music)'}) called: success ({u'muted': True, u'name': u'Line 1 (Streaming Music)', u'volume': 0.20000000298023224})>
```
 ...note that the name of the key is `muted`

....and then:

```
print source.getMute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/obswebsocket/requests.py", line 831, in getMute
    return self.datain["mute"]
KeyError: 'mute'
```
...note the key being used by getMute() is `mute`.

This is with obs-websocket 4.6.1 on the other end.

**Comment by tt2468** [comment]
Could you open a pull request for this?

**Comment by elfchief** [comment]
You're going to make me put forth effort for my free software?!?!

...seems reasonable. Gimme a few!

**Comment by elfchief** [comment]
And done.

I think this might actually be a bug in obs-websocket ... maybe ... because they use 'mute' for set and 'muted' for get, which seems wrong. Fixing it would require changing the API though, so fixing it here is probably the better option (though I'll try to remember to take a look and open an issue in the obs-websocket repo tomorrow)

**Comment by Elektordi** [comment]
The problem was corrected in API docs and the requests.py is now correctly generated.
(https://github.com/Palakis/obs-websocket/blame/4.x-current/docs/generated/comments.json#L5343)
