### ISSUE TITLE
datain/out wrong on SetCurrentScene

### ISSUE THREAD

**Issue by rolandf** [Elektordi/obs-websocket-py#3]
Hi,
it seems that there is some confusion to the way parameters are set for SetCurrentScene.

**Comment by Elektordi** [comment]
Hello,

Could you explain your problem?
And please include real python code to highlight the bug.

After checking, everything seems good:

```
class SetCurrentScene(base_classes.BaseRequest):
    def __init__(self, scene_name):
        base_classes.BaseRequest.__init__(self)
        self.name = "SetCurrentScene"
        self.datain["scene-name"] = scene_name
```

and original doc:

> #### "SetCurrentScene"
> Switch to the scene specified in "scene-name".
> 
> __Request fields__ :  
> - **"scene-name"** (string) : name of the scene to switch to.
> 
> __Response__ : always OK if scene exists, error if it doesn't. No additional fields

And this is one the functions I use in my samples, and seen no problem so far.

Regards,

Guillaume

**Comment by rolandf** [comment]
I was not able to set current scene using that version.

My code was:

`#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import time

import logging
logging.basicConfig(level=logging.INFO)

sys.path.append('../')
from obswebsocket import obsws, requests


print requests.__file__

host = "192.168.1.11"
port = 4444
password = "1234"

ws = obsws(host, port, password)
ws.connect()

try:
    print ws.call(requests.GetVersion())
    scenes = ws.call(requests.GetSceneList())
    for s in scenes.getScenes():
        print s
        name = s['name']
        print "Switching to %s"%(name)
        print ws.call(requests.SetCurrentScene(name))
        time.sleep(2)
    print ws.call(requests.SetSourceRender(source='TXT1', render=True, scene_name='Scene2'))
    print ws.call(requests.SetSourceRender(source='TXT2', render=True, scene_name="Scene2"))
    time.sleep(2)
    print ws.call(requests.SetSourceRender(source='TXT1', render=False, scene_name='Scene2'))
    print ws.call(requests.SetSourceRender(source='TXT2', render=False, scene_name="Scene2"))
    print "End of list"

except KeyboardInterrupt:
    pass

ws.disconnect()
`


I had to change datain to dataout as here:

> class SetCurrentScene(base_classes.BaseRequest):
>     def __init__(self, scene_name):
>         base_classes.BaseRequest.__init__(self)
>         self.name = "SetCurrentScene"
>         self.dataout["scene-name"] = scene_name
> 

Same for SetSourceRender, there is a mismatch of datain/out too.

**Comment by Elektordi** [comment]
Thanks for your help. I just have resolved the issue in master.
