### ISSUE TITLE
Additional Objects Required for Class "SetSceneItemProperties"

### ISSUE THREAD

**Issue by rmduddy** [Elektordi/obs-websocket-py#34]
Hi, thanks for excellent work on this library, I am using and appreciating!

There is an issue with the class "SetSceneItemProperties", and possibly others that prevent many fields from being set in OBS.  Wrapper currently sends request as single object with keys and values exactly according to obs-websocket documentation for all possible fields.  Documentation is slightly convoluted however, the correct behavior for this class should be to send an object with nested objects for "Position, Scale, Crop, and Bound".  See comments from haganbmj here:
https://github.com/haganbmj/obs-websocket-js/issues/128

Any field listed in obs-websocket documentation in "x.x" format is referring to a nested object, whereas wrapper is sending the "x.x" documented field as individual keys.

We can observe this in the difference between a set and get request on this class:

<SetSceneItemProperties request ({'item': 'test', 'scene-name': None, '**position.x**': 0, '**position.y**': 0, '**position.alignment**': 5, 'rotation': None, '**scale.x**': None, '**scale.y**': None, '**crop.top**': None, '**crop.bottom**': None, '**crop.left**': None, '**crop.right**': None, 'visible': None, 'locked': None, '**bounds.type**': None, '**bounds.alignment**': None, '**bounds.x**': None, '**bounds.y**': None}) 
called: success ({})>

<GetSceneItemProperties request ({'item': 'test', 'scene-name': None}) called: success (**{'bounds': {'alignment': 0, 'type': 'OBS_BOUNDS_NONE', 'x': 0.0, 'y': 0.0}**, **'crop': {'bottom': 0, 'left': 0, 'right': 0, 'top': 0}**, 'height': 1080.0, 'locked': False, 'name': 'test', '**position': {'alignment': 5, 'x': 1890.0, 'y': 0.0}**, 'rotation': 0.0, **'scale': {'x': 1.0, 'y': 1.0}**, 'sourceHeight': 1080, 'sourceWidth': 2160, 'visible': True, 'width': 2160.0})>

The OBS Logs show that the set request has failed to properly set those parameters that are shown as being nested in the get request (specifically position in this example):

17:47:35.363: [obs-websocket] Request >> '{"item": "test", "scene-name": null, **"position.x": 0, "position.y": 0**, "position.alignment": 5, "rotation": null, "scale.x": null, "scale.y": null, "crop.top": null, "crop.bottom": null, "crop.left": null, "crop.right": null, "visible": null, "locked": null, "bounds.type": null, "bounds.alignment": null, "bounds.x": null, "bounds.y": null, "request-type": "SetSceneItemProperties", "message-id": "3"}'
17:47:35.363: [obs-websocket] Update << '{
17:47:35.363:     "item-id": 4,
17:47:35.363:     "item-name": "test",
17:47:35.363:     "scene-name": "1",
17:47:35.363:     "transform": {
17:47:35.363:         "bounds": {
17:47:35.363:             "alignment": 0,
17:47:35.363:             "type": "OBS_BOUNDS_NONE",
17:47:35.363:             "x": 0.0,
17:47:35.363:             "y": 0.0
17:47:35.363:         },
17:47:35.363:         "crop": {
17:47:35.363:             "bottom": 0,
17:47:35.363:             "left": 0,
17:47:35.363:             "right": 0,
17:47:35.363:             "top": 0
17:47:35.363:         },
17:47:35.363:         "height": 1080.0,
17:47:35.363:         "locked": false,
**17:47:35.363:         "position": {
17:47:35.363:             "alignment": 5,
17:47:35.363:             "x": 1890.0,
17:47:35.363:             "y": 0.0
17:47:35.363:         },**
17:47:35.363:         "rotation": 0.0,
17:47:35.363:         "scale": {
17:47:35.363:             "x": 1.0,
17:47:35.363:             "y": 1.0
17:47:35.363:         },
17:47:35.363:         "sourceHeight": 1080,
17:47:35.363:         "sourceWidth": 2160,
17:47:35.363:         "visible": true,
17:47:35.363:         "width": 2160.0
17:47:35.363:     },
17:47:35.363:     "update-type": "SceneItemTransformChanged"
17:47:35.363: }'
17:47:35.363: [obs-websocket] Response << '{
17:47:35.363:     "message-id": "3",
17:47:35.363:     "status": "ok"

The classes marked in obs-websocket as being deprecated (SetSceneItemPosition, SetSceneItemTransform, SetSceneItemCrop) Are still working correctly with the Wrapper and I am currently using as a work around.  Although I do not currently use it, it should be noted there is no alternative class for setting "Bounds".

I briefly attempted to wrap my head around adding this into code myself but have limited time and skill at the moment (although I may still eventually return to attempt it).   As mentioned above the deprecated classes are working for me but I didn't see any open or closed issue regarding this and figured I would submit in case you were unaware, or obs-websocket eventually drops the older classes.

Thanks again!

**Comment by Elektordi** [comment]
Just fixed this in master. Here is an example:

```
In [2]: item = ws.call(requests.GetSceneItemProperties('Test'))

In [3]: print(item.getPosition())
{'alignment': 5, 'x': 0.0, 'y': 0.0}

In [4]: ws.call(requests.SetSceneItemProperties('Test', position={'x':50, 'y':50}))
Out[4]: <SetSceneItemProperties request ({'item': 'Test', 'scale': None, 'locked': None, 'bounds': None, 'crop': None, 'visible': None, 'position': {'x': 50, 'y': 50}, 'rotation': None, 'scene-name': None}) called: success ({})>

In [5]: item = ws.call(requests.GetSceneItemProperties('Test'))

In [6]: print(item.getPosition())
{'alignment': 5, 'x': 50.0, 'y': 50.0}
```

Could you try and tell me if it solves your problem?
