### ISSUE TITLE
Can't reproduce a command.

### ISSUE THREAD

**Issue by MarioMey** [Elektordi/obs-websocket-py#38]
Sorry if this does not belong here... I want to change the opacity of a filter. I read in a obs-websocket issue that somebody uses SetSourceFilterSettings:
```
// camera
    await obs.send(
      "SetSourceFilterSettings", {
        sourceName: "SRC_Cam_1",
        filterName: "Color Correction",
        filterSettings: {
          opacity: opacity
        }
      });
```

I would like to do the same with obs-websocket-py. As in Protocol says this:

filterSettings | Object | New settings. These will be merged to the current filter settings.

... I tried sending that "Object" as a dict:

```
(...)
ws.call(requests.SetSourceFilterSettings(sourceName='Source_001', filterName="Color Correction", filterSettings={"opacity": 50}))
```
... but it didn't work. In Protocol says its an "Object"... How to know what to send? Should I create that "Object" before?

**Comment by Elektordi** [comment]
Hello,

Sorry, forgot to answer you. I just tested your code on my computer, it's working perfectly!

Can you try to show fields? To be sure the names are ok:
```
print(ws.call(requests.GetSourceFilters('Source_001')))
print(ws.call(requests.GetSourceFilterInfo('Source_001', 'Color Correction')))
```
or, if you are stuck, try with the master branch of the code: 
```
pip3 install git+https://github.com/Elektordi/obs-websocket-py
```

**Comment by MarioMey** [comment]
And to set them?

It would be awesome if you answer me as fast as you can! In half and an hour I will stream and it would be great to have this working!

**Comment by MarioMey** [comment]
ws.call(requests.SetSourceFilterSettings(source_input, "Color Correction", {"opacity": valor}))

IT WORKED! :D

**Comment by Elektordi** [comment]
Cool! Have a good stream!
