### ISSUE TITLE
TransitionEnd and TransitionVideoEnd missing

### ISSUE THREAD

**Issue by jg-intent** [Elektordi/obs-websocket-py#39]
When triggering a scene change with a transition events are emitted for TransitionEnd and TransitionVideoEnd.  These are not defined in events.py.

I've installed via pip, if that explains anything.

**Comment by Elektordi** [comment]
Those are defined in the last events.py in master: https://github.com/Elektordi/obs-websocket-py/blob/master/obswebsocket/events.py#L995

You can try to install it in a venv to test. In your venv, clone the repo or use `pip3 install git+https://github.com/Elektordi/obs-websocket-py`.

**Comment by nitinthewiz** [comment]
Installing using `pip3 install git+https://github.com/Elektordi/obs-websocket-py` definitely fixes it. Thanks!
