### ISSUE TITLE
Ignores 'with_transition_name'

### ISSUE THREAD

**Issue by nat2001** [Elektordi/obs-websocket-py#40]
Quite likely I'm doing something wrong. Calling TransitionToProgram works, but uses whatever transition is set in OBS, not what I specify

**Comment by Elektordi** [comment]
Bug already fixed in #34.

The fix is not yet in pip, but you can try to install the new version in a venv to test. In your venv, clone the repo or use `pip3 install git+https://github.com/Elektordi/obs-websocket-py`.

Then you can use:
```
ws.call(requests.TransitionToProgram({'name': 'Stinger'}))
```

**Comment by nat2001** [comment]
Thanks, got it working now
