### ISSUE TITLE
Updates for obs-websocket 4.8 functions

### ISSUE THREAD

**Issue by bbernstein** [Elektordi/obs-websocket-py#45]
Awesome project. I'm making great use of this library.

I'm noticing some warnings about some events that are not recognized by obx-websocket-py but that I see documented in obx-websocket 4.8.

A two that are filling me with the most warnings are:

```
TransitionVideoEnd
TransitionEnd
```

I don't know if this is in-progress or if there's a process for adding more events to the code.

**Comment by SLiX69** [comment]
you could try this #47

**Comment by Elektordi** [comment]
Hello,

Fixed on master. Will be included in version 0.5.2 on PyPI, planned for this evening...

Best regards,
