### ISSUE TITLE
New obs-websocket features not supported

### ISSUE THREAD

**Issue by DhSufi** [Elektordi/obs-websocket-py#49]
Hello Elektordi,

First of all, thank you so much for your awesome work, I really appreciate it.

Recently, obs-websocket has been updated with new features (and also will introduce some more in next release) which are not supported buy obs-websocket-py. For example CreateScene [#576](https://github.com/Palakis/obs-websocket/issues/576#issuecomment-673758191). I also wanted to use new feature [OpenProjector](https://github.com/Palakis/obs-websocket/releases) but I neither could. Will be possible to use them in the future? I am learning programming and my skill is not very good right now, otherwise I would help you to do it.

Thank you for your time.
Best regards.

**Comment by Elektordi** [comment]
Hello,

Fixed on master. Will be included in version 0.5.2 on PyPI, planned for this evening...

Best regards,

**Comment by DhSufi** [comment]
Thank you so much!!
