### ISSUE TITLE
SetVolume argument order changed

### ISSUE THREAD

**Issue by marcan** [Elektordi/obs-websocket-py#53]
76cdd5b changed the signature for SetVolume from 

```def __init__(self, source, volume):```

to

```def __init__(self, volume, source, useDecibel=None):```

This broke API compatibility and that argument order doesn't make any sense (compared to other requests).

**Comment by Elektordi** [comment]
This is linked with #50 , I didn't realized it also affects parameters...

**Comment by Elektordi** [comment]
@marcan update pushed to PyPI (pip) just now!
