### ISSUE TITLE
Lack of parameters in 'SetSceneItemProperties'

### ISSUE THREAD

**Issue by DhSufi** [Elektordi/obs-websocket-py#56]
Hello again,

I am trying to make a source move animation. However I could not find the way of setting the following parameters:

**'height'
'width'
'sourceHeight'
'sourceWidth'**
(Also less important/meaningless: _'itemId', 'name'_)

Maybe it is currently possible but I spent a lot of time trying to set _'height', 'width', 'sourceHeight' and 'sourceWidth'_ but I could not find the way.

On the other hand, when running the move animation (video attached) the _**'ws.call'**_  takes a lot of time between steps because of callback, so the animation it is not smooth enought. I tried to use _**'ws.send'**_ but it gives me an error.  Any advice?

Thank you in advance. Best regards.

https://user-images.githubusercontent.com/75437459/103487226-1f7c2f00-4e04-11eb-94d0-fd6406c4c5fc.mp4

**Comment by Elektordi** [comment]
Hello,

What request are you using? If you are using SetSourceSettings, there is a parameter sourceSettings where you are supposed to use a dict with the required parameters. Or if you are using SetSceneItemProperties you may have to change the values scale.x and scale.y, but in python you have to set scale to a dict with keys x and y.

And for the animation speed, using websockets are not the best for quick timed changes, you should use the script system inside OBS (https://obsproject.com/docs/scripting.html).
But I'm working on a rework on the callback (#37) you can try the test-37 branch if you want.

**Comment by DhSufi** [comment]
Thank you so much, I was using "SetSceneItemProperties". and that worked as you said!! Thanks again.
