### ISSUE TITLE
WebSocket Connection / Websocket client disconnected Message

### ISSUE THREAD

**Issue by Alyss-Swanson** [Elektordi/obs-websocket-py#57]
I'm relatively new to using the obs-websocket-py and should quickly admit that I might easily be missing something.  That said, however, I've written a very simple scene change process that is as follows;

import sys
import obswebsocket
import obswebsocket.requests

def main():
    client = obswebsocket.obsws("localhost", 4444)
    client.connect()
    scene = sys.argv[1]
    response = client.call(obswebsocket.requests.SetCurrentScene(scene))
    client.disconnect()
    return 0

if __name__ == "__main__":
    main()

When I run this code I get a message box twice when I call ths procedure; one message that says "New Websocket connection /n Client [::1]:xxxxx connected" and then another message shortly after reading "Web client disconnected /n Client unknown disconnected" 

Firstly, I'm wondering if there is some way to turn off or hide these messages?

I'm also wondering if I truly need to connect and disconnect as part of the scene change process.  Could I, for example, connect once and then only disconnect when I'm totally done, which may be an hour or more later?  I'm wonderingalso if that would help to improve the throughput of the scenechange() process as I've programmed it.

Your thoughts and suggestions are very much appreciated.

**Comment by iarspider** [comment]
You can disable notifications in OBS WebSocket config (Tools -> OBS WebSocket Web server settings -> uncheck Enable System Tray Alerts). Yes, you totally can connect once and disconnect when done. Or just end the script without disconnecting - this will work as well.

**Comment by Alyss-Swanson** [comment]
Thank you so very much for being so very responsive and helpful.  It is deeply appreciated.  Best wishes for a wonderful New Year.  May it be a season of great peace and joy for you and all those in your life.

Warmly,
-Alyss

**Comment by Elektordi** [comment]
Hello,

I confirm, you can stay connected forever, there is a dedicated thread which keeps the socket alive!

Best regards,
