### ISSUE TITLE
Connect to ngrok tunnel using obs-websocket-py

### ISSUE THREAD

**Issue by rahulsrinivasan1** [Elektordi/obs-websocket-py#65]
Hello.
I have tunneled the obs websocket port (4444) using ngrok.
I am able to access obs studio remotely using http://obs-web.niek.tv/.
But im not able to connect using obs-websocket-py using a python script. 
How to provide the (host, port) to this library so i can connect remotely using python.
Thanks in advance.

**Comment by Elektordi** [comment]
If case your public url is https://xxxxx.ngrok.io/ you can use:

```
host = "xxxxx.ngrok.io"
port = 443
```

If you are using http instead of https, use `port = 80`.
Please test and confirm if it works!

**Comment by rahulsrinivasan1** [comment]
@Elektordi 
Thank you so much. It worked.
