### ISSUE TITLE
Not working with OBS 28.0.0 (obs-websocket v5)

### ISSUE THREAD

**Issue by pkoerner81929** [Elektordi/obs-websocket-py#77]
The latest release of OBS is supporting the new obs-websocket v5 interface. This is not compatible with previous 4.9.1.

An updated version of obs-websocket-py is required.

See OBS Dev Blog: https://obsproject.com/blog/obs-studio-and-obs-websocket-join-forces

"While the release is a standalone plugin meant to be run with OBS Studio 27.2, we will be including version 5 with all downloads of OBS Studio starting with version 28.0.0. Including obs-websocket v5 by default will help drive adoption of the new protocol, and we expect it to benefit the third-party scripts and tools ecosystem long-term by bringing official support to the API that many of them depend on.

To install 5.0.1, check out the [release available on GitHub](https://github.com/obsproject/obs-websocket/releases/tag/5.0.1). Please bear in mind that obs-websocket v5 uses a new protocol that not all tools support, so you may need to additionally install the 4.9.1-compat version to continue using those tools. For a list of software tools that already support the new protocol, see [here](https://github.com/obsproject/obs-websocket#client-software).

Many existing tools will require the previous version of obs-websocket, 4.9.1-compat, in order to continue working until such time as those tools are updated. This version can be installed alongside v5 and will not conflict, and can safely be removed at a later date once any tools you may be using are updated to the new version. That version can be found alongside the download links for 5.0.1 on the release page."

**Comment by kozaka-tv** [comment]
+1 for this! Would be so great to get an update and merge all the pull requests....and continue this great project!

**Comment by Elektordi** [comment]
Just to let you know, version 1.0 just got deployed on pypi!
https://github.com/Elektordi/obs-websocket-py/releases/tag/1.0
