### ISSUE TITLE
How to add image source in scene?

### ISSUE THREAD

**Issue by tororo1066** [Elektordi/obs-websocket-py#78]
How do I get the image source to appear on the obs scene?

I'm trying this:
`requests.CreateSource("info_test", "image_source", "scene",
                                          "{'file': 'C:/Users/UserName/Pictures/screenshot.png'}", True)`
but it didn't specify the path to the image.

I use DeepL translation.

**Comment by MewCrit** [comment]
Hi I'm also looking for this any answer?

**Comment by tororo1066** [comment]
It worked for me.
```python
requests.CreateSource(img_info, "image_source", scene, {'file': os.path.abspath("image.png")}, False)
```
