### ISSUE TITLE
PROTOCOL.md cannot be parsed automatically

### ISSUE THREAD

**Issue by KirillMysnik** [Elektordi/obs-websocket-py#8]
## Message
My whole message of this issue is "`PROTOCOL.md` cannot be parsed automatically".

## Why?
Because given the complexity of matter it tries to declare, it needs more accurate description. [`PROTOCOL.md`](https://github.com/Palakis/obs-websocket/blob/master/PROTOCOL.md) is full of typos and doesn't represent their protocol correctly.

## `generate_classes.py`
Even if `PROTOCOL.md` was perfect, current architecture of `obs-websocket-py` (particularly `generate_classes.py`) doesn't support creating requests like [`StartStreaming`](https://github.com/Palakis/obs-websocket/blob/master/PROTOCOL.md#startstreaming). Let's have a look at that request:

---

__Request fields__ : 
- **"stream"** (object; optional) : If specified allows for special configuration of the stream
 
The 'stream' object has the following fields:
- **"settings"** (object; optional) : The settings for the stream
- **"type"** (string; optional) : If specified ensures the type of the stream matches the given type (usually 'rtmp\_custom' or 'rtmp\_common').  If the currently configured stream type does not match the given stream type, all settings must be specified in the 'settings' object or an error will occur starting the stream.
- **"metadata"** (object; optional) : Adds the given object parameters as encoded query string parameters to the 'key' of the RTMP stream.  Used to pass data to the RTMP service about the stream.

The 'settings' object has the following fields:
- **"server"** (string; optional) : The publish URL
- **"key"** (string; optional) : The publish key of the stream
- **"use-auth"** (bool; optional) : should authentication be used when connecting to the streaming server
- **"username"** (string; optional) : if authentication is enabled, the username for access to the streaming server. Ignored if 'use-auth' is not specified as 'true'.
- **"password"** (string; optional) : if authentication is enabled, the password for access to the streaming server. Ignored if 'use-auth' is not specified as 'true'.

The 'metadata' object supports passing any string, numeric or boolean field.
  
__Response__ : Error if streaming is already active, OK otherwise. No additional fields.  

---

So there's only one field to that request. And it's an object that has (besides other fields) two more object fields - `settings` and `metadata`.
Plus there's this `metadata` object that is unique accross protocol in sense that it can inlude arbitrary fields.

Time to look at the class generated by the `generate_classes.py`:

```python
class StartStreaming(base_classes.BaseRequest):
    def __init__(self, stream, settings, type, metadata, server, key, use_auth, username, password):
        base_classes.BaseRequest.__init__(self)
        self.name = "StartStreaming"
        self.dataout["stream"] = stream
        self.dataout["settings"] = settings
        self.dataout["type"] = type
        self.dataout["metadata"] = metadata
        self.dataout["server"] = server
        self.dataout["key"] = key
        self.dataout["use-auth"] = use_auth
        self.dataout["username"] = username
        self.dataout["password"] = password
```
All fields are inserted directly into request. That is wrong and doesn't work. Also all fields are required, no opportunity to skip any of them (while `PROTOCOL.md` declares all of them as optional).

## Maybe a better parser could solve this?
Doubt it. Look at the [`StartStopRecording`](https://github.com/Palakis/obs-websocket/blob/master/PROTOCOL.md#startstoprecording) request. Its only field (`stream`) is not even declared there - we're just told to look it up in another request. We'd need an AI parser to handle all these cases in `PROTOCOL.md`. **MOREOVER,** I suspect that `stream` property doesn't even belong there - it's likely for `StartStopStreaming` request, just was misplaced accidentally in `PROTOCOL.md`. Huh.

## What do you propose?
It's simple, we, err, handle the stuff manually.

As a part of my [Python 3.5+ `asyncio`-based client to `obs-websocket` plugin](https://github.com/KirillMysnik/obs-ws-rc/), I tried to carefully build a [usable representation of their protocol](https://github.com/KirillMysnik/obs-ws-rc/blob/master/obswsrc/protocol.json).

I provide information of all protocol types (like `StreamSettings` type etc), their fields, types of their fields and their "pythonic" fields (`authRequired`'s pythonic one is `auth_required`; `use-auth`'s pythonic one is `use_auth`). Then I provide information of all requests, their responses and all events.

Guess what? I've failed as soon as I received a response for the `GetAuthRequired` request. The fact that `challenge` and `salt` fields are optional (they're sent only if the auth is enabled) is mentioned in the request description, but not anywhere near the fields themselves (usually they detone such fields as "optional" explicitly).

It just confirms the fact that a _maintaining_ is needed, you can't just convert `PROTOCOL.md` to anything useful.

I've already seen a few events that don't provide their "required" fields (probably they forgot to mention those were optional, again), but I'm going to do more tests, and finally build an accurate, usable description of the protocol v4.1.

Feel free to use it. My client builds all classes during runtime, but it's still possible to use that file to build classes offline, too.

**Comment by Elektordi** [comment]
I know :(

More seriously, I did that as a quick and dirty way to implement quickly the API, I'll try to make a full (and manual) rewrite of events.py and requests.py, and drop generate_classes.py

I was also thinking about creating objects representing OBS objects (scenes, media...) and putting methods on them which would call the api controller behind. Could be more interesting and object-oriented that the current "flat" classes I created.
