### ISSUE TITLE
Switch Scene v4 Sample

### ISSUE THREAD

**Issue by AlexisDot** [Elektordi/obs-websocket-py#82]
Just a quick heads-up, the sample seems to be somewhat incorrect, i had to leave out  the `legacy=True` part in the obsws call on line 16 plus the argument for SetCurrentScene on line 24 should be `scene_name` nothing major just wanted to let you know, thanks for the work

**Comment by Elektordi** [comment]
The v4 protocol request "SetCurrentScene" has an argument called "scene-name".
Here is the revelent documentation: https://github.com/obsproject/obs-websocket/blob/4.x-compat/docs/generated/protocol.md#setcurrentscene
I also tested it on OBS 27.2.4 and obs-websocket 4.7.0

If you needed to change the name for the call to work, could you indicate the OBS and obs-websocket versions you are using?

**Comment by Elektordi** [comment]
Thanks for the info, I haven't tested the "compat" version yet... I didn't know they changed the protocol since the old v4 version...

**Comment by Elektordi** [comment]
Just tested OBS 29.0.2 with obs-websocket-4.9.1-compat, the switch_scenes_v4.py sample is working perfectly!
(with `scene-name` parameter)

But since you are using OBS 29.0.1, which support new v5 protocol, have you tested the switch_scenes.py sample?

**Comment by AlexisDot** [comment]
I tested both samples prior to posting here, the mentioned changes were necessary to get it to run, like i said it's not a major issue, not sure why it required the underscore instead of the dash but it works
