### ISSUE TITLE
SetSourceSettings expects one argument but 3 were given

### ISSUE THREAD

**Issue by BeeFox-sys** [Elektordi/obs-websocket-py#84]
```
    client.call(requests.SetSourceSettings(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Baserequests.__init__() takes 1 positional argument but 3 were given
```

```py
client.call(requests.SetSourceSettings(
                    "source-name",
                    {"file": file_name}))
```

I am not sure why this nolonger works, it worked up until the requests made to be generated

**Comment by NengQian** [comment]
Same issue here, I believe this time you should intead use positional argument but use keyword arguement.
But the question is, where can I find the correct keyword args' name?

**Comment by Elektordi** [comment]
@BeeFox-sys All requests now requires keyword (named) arguments.
SetSourceSettings does not exist in new (v5) protocol, so I suppose you are using the old v4 protocol, you can find arguments here:
https://github.com/obsproject/obs-websocket/blob/4.x-compat/docs/generated/protocol.md#setsourcesettings

In your case, you can use:
```
client.call(requests.SetSourceSettings(
                    sourceName="source-name",
                    sourceSettings={"file": file_name}
                    ))
```

**Comment by AlaricBell** [comment]
Hi @Elektordi I am having the same issue with V5, is there a documentation where I can check the available requests objects and their expected parameters?
I am fairly new in OBS scripting, probably I just missed the documentations somehow.

**Comment by riivrtwo** [comment]
Is there a v5 method for accessing/modifying the file path of an image source in a similar way?

**Comment by riivrtwo** [comment]
> Is there a v5 method for accessing/modifying the file path of an image source in a similar way?

nm, SetSourceSettings has been moved to SetInputSettings etc
